// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProductRestApi.Models;

#nullable disable

namespace ProductRestApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProductRestApi.Classes.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductDiscount")
                        .HasColumnType("real");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("ProductPrice")
                        .HasColumnType("real");

                    b.Property<int>("proType")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductDescription = "Are shoes Mate",
                            ProductDiscount = 0.2f,
                            ProductName = "Shoes",
                            ProductPrice = 43f,
                            proType = 0
                        },
                        new
                        {
                            ProductId = 2,
                            ProductDescription = "Is massage Mate",
                            ProductDiscount = 0f,
                            ProductName = "Massages",
                            ProductPrice = 20f,
                            proType = 1
                        },
                        new
                        {
                            ProductId = 3,
                            ProductDescription = "Fuchiball Fuchiball ronaldhino",
                            ProductDiscount = 0.15f,
                            ProductName = "football",
                            ProductPrice = 15f,
                            proType = 0
                        },
                        new
                        {
                            ProductId = 4,
                            ProductDescription = "Bruh",
                            ProductDiscount = 0f,
                            ProductName = "Dont know",
                            ProductPrice = 10f,
                            proType = 2
                        },
                        new
                        {
                            ProductId = 5,
                            ProductDescription = "Unix system",
                            ProductDiscount = 0.3f,
                            ProductName = "Computer",
                            ProductPrice = 250f,
                            proType = 0
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
