BEGIN;

DROP TABLE IF EXISTS ENTRADAS;
DROP SEQUENCE IF EXISTS SEQ_ENTRADAS;

CREATE TABLE IF NOT EXISTS ENTRADAS (
    ID_ENTRADA  VARCHAR(6),
    PELICULA    VARCHAR(50),
    FECHA       DATE,
    BUTACA      NUMERIC(100),
    PVP         NUMERIC(4, 2),

    CONSTRAINT "PK_ENTRADAS"            PRIMARY KEY (ID_ENTRADA),
    CONSTRAINT "NN_ENTRADAS.PELICULA"   CHECK ( PELICULA IS NOT NULL ),
    CONSTRAINT "NN_ENTRADAS.FECHA"      CHECK ( FECHA IS NOT NULL ),
    CONSTRAINT "NN_ENTRADAS.BUTACA"     CHECK ( BUTACA IS NOT NULL ),
    CONSTRAINT "NN_ENTRADAS.PVP"        CHECK ( PVP IS NOT NULL ),
    CONSTRAINT "CH_ENTRADAS.BUTACA"     CHECK ( BUTACA >= 0 ),
    CONSTRAINT "CH_ENTRADAS.PVP"        CHECK ( PVP > 0 )
    );

CREATE SEQUENCE SEQ_ENTRADAS MINVALUE 1 MAXVALUE 999998 START WITH 1 INCREMENT BY 1;

INSERT INTO ENTRADAS(ID_ENTRADA, PELICULA, FECHA, BUTACA, PVP)
VALUES
    (nextval('SEQ_ENTRADAS'), 'Mision imposible: Sentencia final', DATE('2025-05-30'), 11, 6),
    (nextval('SEQ_ENTRADAS'), 'Mision imposible: Sentencia final', DATE('2025-05-30'), 25, 6),
    (nextval('SEQ_ENTRADAS'), 'Mision imposible: Sentencia final', DATE('2025-05-31'), 3, 6),
    (nextval('SEQ_ENTRADAS'), 'Lilo y Stich', DATE('2025-06-02'), 11, 4.5),
    (nextval('SEQ_ENTRADAS'), 'Lilo y Stich', DATE('2025-06-02'), 5, 4.5);

COMMIT;
